
import { ProductCategory, Product } from './types';

export const PRODUCTS_DATA: Product[] = [
  // Dental Products
  {
    id: 'plan-dental-total',
    name: 'Plan Dental Total',
    category: ProductCategory.Dental,
    strongPoint: 'Cobertura dental completa sin copagos.',
    features: [
      'Solo disponible para canal asegurador',
      'No disponible para clientes Caixa',
      'Cobertura dental completa',
      'Sin copago en servicios dentales',
      'Acceso a profesionales especializados',
      'Clínicas propias y colaboradoras',
      'Sin límites de visitas anuales',
      'Tratamientos preventivos incluidos',
    ],
    advantages: [
      'Cobertura dental completa',
      'Sin copagos en ningún tratamiento',
      'Sin periodos de carencia',
      'Incluye tratamientos de ortodoncia',
    ],
    limitations: [
      'No disponible para clientes Caixa',
      'Limitado a cuadro médico dental',
      'Puede haber lista de espera',
    ],
    defenseArguments: [
      'Ofrece una cobertura dental completa sin copagos para clientes del canal asegurador.',
      'Es la opción más económica a largo plazo para quienes necesitan tratamientos dentales frecuentes o complejos.',
      'La mejor opción en relación calidad-precio en cobertura dental para clientes del canal asegurador.',
    ],
    idealClient: ['Cliente canal asegurador', 'Busca cobertura completa', 'Sin copagos'],
  },
  {
    id: 'adeslas-dental-familia',
    name: 'Adeslas Dental / Dental Familia',
    category: ProductCategory.Dental,
    strongPoint: 'Ahorro significativo con franquicia.',
    features: [
      'Disponible para todos los clientes',
      'Con franquicia dental',
      'Modalidades: Individual y Familiar',
      'Pago directo en clínica al momento',
      'Acceso a profesionales especializados',
      'Sin límites de visitas anuales',
    ],
    advantages: [
      'Hasta 35% de ahorro respecto a precio sin seguro',
      'Disponible para todos los perfiles de cliente',
      'Modalidad familiar con descuentos adicionales',
      'Sin periodos de carencia',
    ],
    limitations: ['Tiene franquicia, no es sin copago', 'Limitado a cuadro médico dental', 'Puede haber lista de espera en algunas clínicas'],
    defenseArguments: [
      'La franquicia permite un ahorro significativo de hasta 35%.',
      'Es la opción más equilibrada entre precio y cobertura para la mayoría de clientes.',
      'No tiene copagos adicionales más allá de la franquicia establecida.',
    ],
    idealClient: ['Busca ahorro', 'Accesible', 'Familias'],
  },
  {
    id: 'dental-max',
    name: 'Dental Max',
    category: ProductCategory.Dental,
    strongPoint: 'Precio que se reduce progresivamente cada año.',
    features: [
      'Precio inicial: 12€/mes, desciende progresivamente a 6€/mes',
      '10% descuento a partir de 3 asegurados',
      'Sin periodos de carencia',
    ],
    advantages: [
      'Precio reducido progresivamente',
      'Mejor precio a largo plazo del mercado',
      'Descuentos adicionales para familias o grupos',
      'Sin copagos adicionales más allá de la cuota mensual',
    ],
    limitations: [
      'Precio inicial más alto que otros productos',
      'Requiere compromiso a largo plazo para mejor precio',
      'Limitado a cuadro médico dental',
    ],
    defenseArguments: [
      'Aunque el precio inicial es de 12€, se reduce progresivamente hasta 6€, ofreciendo el mejor precio a largo plazo.',
      'Es la opción más económica para clientes fieles que buscan un seguro dental a largo plazo.',
      'Con el 10% de descuento adicional, se convierte en la opción más competitiva del mercado.',
    ],
    idealClient: ['Largo plazo', 'Busca mejor precio', 'Familias numerosas'],
  },

  // Ambulatory Products
  {
    id: 'adeslas-basico-familia',
    name: 'Adeslas Básico / Básico Familia',
    category: ProductCategory.Ambulatory,
    strongPoint: 'Complemento perfecto a la Seguridad Social para agilizar consultas.',
    features: [
      'Antiguo seguro que no se comercializa pero sigue vigente',
      'Buen complemento a la Seguridad Social',
      'Acelera tiempo y procesos de prevención',
      'No cubre hospitalizaciones ni intervenciones quirúrgicas',
      'Sin tiempos de espera prolongados',
    ],
    advantages: [
      'Acelera tiempos de espera',
      'Excelente complemento a la Seguridad Social',
      'Precio accesible',
      'Cobertura de prevención y consultas',
      'Modalidad familiar disponible',
    ],
    limitations: [
      'No se comercializa actualmente',
      'No cubre hospitalizaciones',
      'No incluye intervenciones quirúrgicas',
      'Sin cobertura dental incluida',
      'Limitado a cuadro médico de Adeslas',
    ],
    defenseArguments: [
      'Aunque es un producto antiguo, sigue siendo muy vigente y ofrece una excelente relación calidad-precio.',
      'Es el complemento perfecto para quienes ya tienen cobertura hospitalaria pero quieren agilizar consultas y pruebas.',
      'Permite acceso rápido a especialistas y pruebas diagnósticas sin los largos tiempos de espera de la Seguridad Social.',
    ],
    idealClient: ['Tiene cobertura hospitalaria', 'Busca agilizar consultas', 'Precio económico'],
  },
  {
    id: 'adeslas-go',
    name: 'Adeslas GO',
    category: ProductCategory.Ambulatory,
    strongPoint: 'Valor inmediato con 3 actos gratuitos anuales y bonificaciones.',
    features: [
      'Plan con más opciones',
      '3 primeros actos anuales gratuitos (máx. 16€)',
      'Se renuevan cada año',
      '25% más baratos los copagos a partir del 2º año',
      '10% descuento a partir del segundo asegurado',
      'No cubre hospitalizaciones',
    ],
    advantages: [
      '3 actos gratuitos anuales',
      'Bonificaciones progresivas con el tiempo',
      'Descuentos por volumen de asegurados',
      'Rápido acceso a consultas y pruebas',
      'Sin tiempos de espera prolongados',
    ],
    limitations: [
      'Límite de 16€ para actos gratuitos',
      'Requiere renovación anual para mantener beneficios',
      'No cubre hospitalizaciones',
      'Sin cobertura dental incluida',
      'Limitado a cuadro médico de Adeslas',
    ],
    defenseArguments: [
      'Los 3 primeros actos gratuitos anuales ofrecen un valor inmediato que compensa la inversión.',
      'Las bonificaciones progresivas a partir del segundo año hacen que el seguro sea más rentable con el tiempo.',
      'El 10% de descuento adicional por volumen lo convierte en una excelente opción para familias o grupos.',
    ],
    idealClient: ['Uso frecuente', 'Busca beneficios inmediatos', 'Familias'],
  },

  // Hospital Products
  {
    id: 'adeslas-plena',
    name: 'Adeslas Plena',
    category: ProductCategory.Hospital,
    strongPoint: 'Copagos muy reducidos con cobertura completa.',
    features: [
      'Con copagos muy reducidos',
      'Misma cobertura con menos pago mensual',
      'Solo se paga el copago en caso de uso',
      'Cubre hospitalización sin límite de días',
      'No incluye cobertura dental',
      'Cobertura de hospitalización completa',
    ],
    advantages: [
      'Copagos muy reducidos',
      'Cobertura completa (ambulatoria + hospitalaria)',
      'Solo se paga cuando se utilizan los servicios',
      'Sin límite de días de hospitalización',
      'Hasta 20 sesiones de psicoterapia',
    ],
    limitations: [
      'Tiene copagos (aunque reducidos)',
      'No incluye cobertura fuera del cuadro médico',
      'Sin cobertura dental incluida',
      'Cobertura limitada en el extranjero',
      'Periodos de carencia aplicables',
    ],
    defenseArguments: [
      'Permite acceder a una cobertura completa a un precio mensual más bajo.',
      'Es más económico para quienes usan poco los servicios médicos.',
      'Ofrece la mejor relación calidad-precio para quienes buscan cobertura hospitalaria completa sin un desembolso mensual elevado.',
    ],
    idealClient: ['Bajo uso médico', 'Busca cobertura completa', 'Precio controlado'],
  },
  {
    id: 'adeslas-plena-plus',
    name: 'Adeslas Plena Plus',
    category: ProductCategory.Hospital,
    strongPoint: 'Sin copagos con cobertura completa.',
    features: [
      'Sin copagos en ningún servicio',
      'Incluye hospitalización completa',
      '12.000€ de cobertura en el extranjero',
      '20 sesiones de psicoterapia',
      '12 sesiones de podología al año',
    ],
    advantages: [
      'Sin copagos en ningún servicio',
      'Cobertura completa (ambulatoria + hospitalaria)',
      'Psicoterapia incluida (20 sesiones)',
      'Podología incluida (12 sesiones/año)',
      'Sin límite de días de hospitalización',
    ],
    limitations: [
      'Precio mensual más elevado que Adeslas Plena',
      'No incluye cobertura fuera del cuadro médico',
      'Sin cobertura dental incluida',
      'Cobertura en extranjero limitada a 12.000€',
      'Periodos de carencia aplicables',
    ],
    defenseArguments: [
      'Aunque el precio es más elevado, la ausencia de copagos y los servicios adicionales lo convierten en una opción muy completa.',
      'Es predecible en costes, sin sorpresas al utilizar los servicios médicos.',
      'La inclusión de psicoterapia y podología representa un valor añadido significativo.',
    ],
    idealClient: ['Uso frecuente', 'Busca previsibilidad', 'Viajeros'],
  },
  {
    id: 'adeslas-premium',
    name: 'Adeslas Premium',
    category: ProductCategory.Hospital,
    strongPoint: 'Máxima libertad de elección sin restricciones.',
    features: [
        'Sin copagos fuera del cuadro médico',
        'Cobertura integral dentro y fuera del cuadro médico',
        'Cobertura en el extranjero sin límites',
        'Libertad para elegir cualquier médico o centro',
        'Hospitalización completa sin límites',
    ],
    advantages: [
        'Libertad total para elegir cualquier médico o centro',
        'Cobertura completa sin restricciones geográficas',
        'Cobertura internacional sin límites',
        'Hospitalización en cualquier centro sin límites',
    ],
    limitations: [
        'Es la póliza más cara de todas',
        'No incluye cobertura dental específica',
        'Periodos de carencia aplicables',
        'Puede requerir autorizaciones para ciertos tratamientos',
    ],
    defenseArguments: [
        'Ofrece libertad total para elegir médico o centro sin preocuparse por copagos ni restricciones.',
        'Es la opción más completa y flexible del mercado, ideal para quienes valoran la libertad de elección por encima del precio.',
        'La cobertura internacional sin límites la convierte en la mejor opción para viajeros frecuentes o residentes en el extranjero.',
    ],
    idealClient: ['Valora libertad', 'Alto poder adquisitivo', 'Exige máxima flexibilidad'],
  },
  {
    id: 'adeslas-expert',
    name: 'Adeslas Expert',
    category: ProductCategory.Hospital,
    strongPoint: 'Acceso exclusivo a la Clínica Universitaria de Navarra (CUN).',
    features: [
        'Con copagos reducidos',
        'Acceso a la CUN - Clínica Universitaria de Navarra',
        'Similar a Adeslas Plena pero con acceso a la CUN',
        'Carencia de 10 meses en hospitalización',
        'Cubre hospitalización completa',
    ],
    advantages: [
        'Acceso a la CUN, centro de prestigio',
        'Copagos reducidos comparados con otros seguros',
        'Cobertura completa (ambulatoria + hospitalaria)',
        'Acceso a especialistas de élite en la CUN',
        'Acceso a tecnología avanzada y tratamientos innovadores',
    ],
    limitations: [
        'Tiene copagos (aunque reducidos)',
        'Carencia de 10 meses en hospitalización (2 meses más)',
        'No incluye cobertura fuera del cuadro médico',
        'Sin cobertura dental incluida',
        'Cobertura limitada en el extranjero',
    ],
    defenseArguments: [
        'El acceso a la CUN, uno de los centros médicos más prestigiosos de España, justifica los copagos y el periodo de carencia más largo.',
        'Ofrece una calidad asistencial superior con acceso a tecnología de vanguardia y especialistas de élite.',
        'Para quienes valoran la máxima calidad médica y el acceso a un centro de referencia internacional, los copagos adicionales son una inversión.',
    ],
    idealClient: ['Valora calidad', 'Busca centros de élite', 'Dispuesto a pagar más'],
  },

  // MyBox Products
  {
    id: 'mybox-salud',
    name: 'MyBox Salud',
    category: ProductCategory.MyBox,
    strongPoint: 'Póliza trianual con precio estable y reembolso en farmacia.',
    features: [
        'Cobertura dental y salud incluidas',
        'Póliza trianual (3 años de precio estable)',
        'Compromiso de respuesta 24-48 horas',
        '50% de reembolso en farmacia',
        'No se puede dar de baja por desempleo (3 años)',
    ],
    advantages: [
        'Cobertura completa dental y de salud',
        'Precio estable durante 3 años',
        'Compromiso de respuesta rápido (24-48h)',
        'Reembolso en farmacia del 50%',
        'Indemnización de 200€ si no se cumple el plazo',
    ],
    limitations: [
        'Compromiso de 3 años (póliza trianual)',
        'No se puede solicitar baja por desempleo',
        'Puede conllevar consecuencias legales si no se cumple',
        'Limitado a cuadro médico de Adeslas',
        'Periodos de carencia aplicables',
    ],
    defenseArguments: [
        'El compromiso de 3 años permite mantener un precio estable, protegiéndote de futuras subidas.',
        'El compromiso de respuesta con indemnización garantiza un servicio rápido y eficiente.',
        'El reembolso del 50% en farmacia es un beneficio único que no ofrecen otros productos y supone un ahorro significativo.',
    ],
    idealClient: ['Busca estabilidad', 'Uso medicamentos frecuente', 'Compromiso largo plazo'],
  },
  {
    id: 'mybox-senior',
    name: 'MyBox Senior',
    category: ProductCategory.MyBox,
    strongPoint: 'Diseñado específicamente para mayores de 63 años.',
    features: [
        'Contratable a partir de los 63 años',
        'Siempre tiene copagos',
        'Derivación mediante asesor de salud (copago 0€ en especialidades comunes)',
        '50% de reembolso en podología y fisioterapia',
    ],
    advantages: [
        'Diseñado específicamente para mayores de 63 años',
        'Copago 0€ en especialidades comunes si se utiliza asesor',
        'Reembolso en podología y fisioterapia (50%)',
        'Asesor de salud para seguimiento personalizado',
        'Cobertura dental completa incluida',
    ],
    limitations: [
        'Siempre tiene copagos (excepto con asesor)',
        'Requiere derivación por asesor de salud',
        'Límite de 500€ año en reembolsos',
        'Limitado a cuadro médico de Adeslas',
        'Periodos de carencia aplicables',
    ],
    defenseArguments: [
        'Está diseñado específicamente para mayores de 63 años con sus necesidades particulares de salud.',
        'El sistema de derivación por asesor de salud garantiza un seguimiento adecuado y personalizado.',
        'Los copagos 0 en especialidades comunes lo hacen muy económico para usos frecuentes.',
    ],
    idealClient: ['Mayores de 63', 'Necesita seguimiento', 'Uso frecuente especialidades'],
  },

  // Business Products
  {
    id: 'mybox-salud-negocios',
    name: 'MyBox Salud Negocios y Empresas',
    category: ProductCategory.Business,
    strongPoint: 'Flexibilidad para gestionar cambios de personal con precio estable.',
    features: [
        'Misma continuidad de 3 años',
        'Se puede dar de baja a empleados que ya no están en la empresa',
        'No se puede dar de baja a familiares asignados a éstos',
        'Cobertura dental completa incluida',
        '50% de reembolso en farmacia',
    ],
    advantages: [
        'Precio estable durante 3 años',
        'Flexibilidad para dar de baja a empleados',
        'Cobertura completa para empleados y familiares',
        'Reembolso en farmacia del 50%',
    ],
    limitations: [
        'No se puede dar de baja a familiares asignados',
        'Compromiso de 3 años (póliza trianual)',
        'Puede conllevar consecuencias legales si no se cumple',
        'Limitado a cuadro médico de Adeslas',
        'Periodos de carencia aplicables',
    ],
    defenseArguments: [
        'El compromiso de 3 años permite mantener un precio estable, protegiendo a la empresa de futuras subidas.',
        'La flexibilidad para dar de baja a empleados lo hace adaptable a los cambios de personal.',
        'Mantener la cobertura para familiares es un beneficio social muy valorado que mejora la satisfacción y retención del talento.',
    ],
    idealClient: ['Empresas estables', 'Rotación moderada', 'Busca predecibilidad'],
  },
  {
    id: 'adeslas-empresas-negocios',
    name: 'Adeslas Empresas y Negocios',
    category: ProductCategory.Business,
    strongPoint: 'Cobertura completa sin compromiso de permanencia.',
    features: [
        'Cobertura ambulatoria completa',
        'Cobertura hospitalaria completa',
        'Para empleados y sus familias',
        'Acceso a cuadro médico amplio',
        'Sin compromiso de permanencia',
    ],
    advantages: [
        'Cobertura completa para empleados',
        'Sin compromiso de permanencia',
        'Gestión simplificada para la empresa',
        'Acceso a cuadro médico amplio',
        'Beneficio social muy valorado',
    ],
    limitations: [
        'No incluye reembolsos ni acceso fuera del cuadro',
        'Puede tener copagos según el plan contratado',
        'Limitado a cuadro médico de Adeslas',
        'Sin cobertura dental específica incluida',
        'Periodos de carencia aplicables',
    ],
    defenseArguments: [
        'Ofrece una cobertura completa tanto ambulatoria como hospitalaria para los empleados, sin compromiso de permanencia.',
        'Permite a las empresas adaptar la póliza a sus necesidades cambiantes sin penalizaciones.',
        'Aunque tiene copagos, estos son reducidos y solo se pagan cuando se utilizan los servicios, optimizando costes.',
    ],
    idealClient: ['Empresas flexibles', 'Rotación variable', 'Busca flexibilidad'],
  },
  {
    id: 'adeslas-extra-empresas',
    name: 'Adeslas Extra Empresas',
    category: ProductCategory.Business,
    strongPoint: 'Máxima flexibilidad con reembolsos y acceso fuera de cuadro.',
    features: [
        'Cobertura ambulatoria completa',
        'Cobertura hospitalaria completa',
        'Con reembolsos incluidos',
        'Acceso dentro y fuera del cuadro médico',
        'Para empleados y sus familias',
    ],
    advantages: [
        'Libertad total para elegir cualquier médico',
        'Reembolsos incluidos para mayor flexibilidad',
        'Cobertura completa sin restricciones',
        'Gestión simplificada para la empresa',
        'Beneficio premium muy valorado',
    ],
    limitations: [
        'Precio más elevado que Adeslas Empresas',
        'Puede tener copagos según el plan contratado',
        'Puede requerir autorizaciones para ciertos tratamientos',
        'Sin cobertura dental específica incluida',
        'Periodos de carencia aplicables',
    ],
    defenseArguments: [
        'Ofrece la máxima flexibilidad al permitir acudir a cualquier médico dentro o fuera del cuadro médico.',
        'La inclusión de reembolsos permite a los empleados elegir libremente sin preocuparse por costes adicionales.',
        'Es la opción más completa y flexible para empresas que quieren ofrecer el mejor servicio a sus empleados sin restricciones.',
    ],
    idealClient: ['Empresas premium', 'Retener talento', 'Beneficio máximo'],
  },
];
